alias c='xclip -selection clipboard -i'
alias ll='ls -alh'
alias s='source venv/bin/activate'
alias n="nvim"
alias ydl="youtube-dl -f bestvideo+bestaudio"
alias penv="python3 -m venv venv && source venv/bin/activate"
alias gp="allblack && git add -A && git commit && git pull && git push"
alias fel="flutter emulators --launch Pixel_3a_API_30_x86"
alias back="cd ~/vege/backend"
alias front="cd ~/vege/frontend"
alias p="python3"
alias ig="cd ~/Downloads/designerlauncher/app && ./designerlauncher.sh"
alias ala="ls -alah" #the great god sees everything
alias byem="find ./ -type f -print0 | xargs -0 dos2unix --"
alias allblack="find ./ -name \"*.py\" -type f -print0 | xargs -0 black --"
alias frun="flask run --port=42069 --host=0.0.0.0"
alias logout="sudo systemctl restart gdm"
alias mp3="youtube-dl --extract-audio --audio-format mp3"
alias brightness="xrandr --output eDP-1 --brightness"
