alias c='xclip -selection clipboard -i'
alias ll='ls -alh'
alias s='source venv/bin/activate'
alias n="nvim"
alias ydl="youtube-dl -f bestvideo+bestaudio"
alias penv="python3 -m venv venv && source venv/bin/activate"
alias gp="git add -A && git commit && git pull && git push"
alias fel="flutter emulators --launch Pixel_3a_API_30_x86"
alias back="cd ~/vege/backend"
alias front="cd ~/vege/frontend"
alias p="python3"
